import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

//szx яыч  SZX  


//Отдельно можно компонент поставить
// component CalculateButton {

//     Button {
//         text: "calculate";
//         primary: true;
//         height: 35px;
//         clicked => {divide-income(income.text)}
//     }
// }

export component AppWindow inherits Window {

    in property <string> results: "";
    callback divide-income(string);

    background: #313e44;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                height: 35px;
               
            }  
        }

        Row{
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter number";
            }
        }

        Row{
          //CalculateButton {}    
           Button {
            text: "calculate";
            primary: true;
            height: 35px;
            clicked => {divide-income(income.text)}
        }
        }

        Row{
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
